[platformio]
default_envs = target-led
src_dir = .

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
monitor_speed = 115200
lib_deps =
    fastled/FastLED@3.10.3
    lewisxhe/SensorLib@0.4.0

[env:target-led]
board = esp32-s3-devkitc-1
build_flags =
    -DBOARD_ESP32S3_MATRIX
    -DARDUINO_USB_CDC_ON_BOOT=1
board_upload.flash_size = 4MB

[env:target-lcd]
board = esp32-s3-devkitc-1
build_flags =
    -DBOARD_ESP32S3_LCD_169
    -DARDUINO_USB_CDC_ON_BOOT=1
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
lib_deps =
    ${env.lib_deps}
    lovyan03/LovyanGFX@1.2.19
    moononournation/GFX Library for Arduino@1.6.5
